### ISSUE TITLE
403 error, spotify is blocking the use of social-connect I believe.

### ISSUE THREAD

**Issue by CharlieS1103** [timll/spotify-group-session#1]
``Uncaught (in promise) ForbiddenError: GET request to https://spclient.wg.spotify.com/social-connect/v2/sessions/current_or_new?local_device_id=&type=REMOTE failed with status code 403
    at d.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)``
Downloaded through marketplace (I don't believe that should impact this though, just thought to include)

**Comment by t1mlange** [comment]
Did you redact the local device id?

Also, do you have Spotify Premium?

**Comment by CharlieS1103** [comment]
Ah, no I do not, it might be a good idea to include that in the readme

**Comment by t1mlange** [comment]
I've added a note in the readme and also included a notification on session creation failure.
