### ISSUE TITLE
Desktop client no longer stays connected.

### ISSUE THREAD

**Issue by Stapleton** [timll/spotify-group-session#10]
Desktop can start or join group sessions, but it gets kicked from the group when theres a song change of any kind. (Starting, stopping, skipping, etc). If it didn't kick itself, then it probably would work. Seems to be 90% working in 2023. Id be happy to give any logs or errors if there are any, as I don't know if those get written to disk, let alone where.

**Comment by t1mlange** [comment]
You can try and open the web console in Spotify (iirc right click on something empty and then inspect element) and look for errors in the console. FYI, this extension does not implement the group logic but rather calls the Spotify API as your mobile device would. In the best case, Spotify just altered their API, and we just need to update some URLs. 

Finding out the more or less secret API is a bit more complex: First, you have to remove the certificate pinning from the current version of the Spotify app and install that patched APK. Then use mitmproxy or something else to intercept the traffic while using the Spotify group sessions.
Though, meanwhile Discord also gained Spotify integration which might allow skipping the hassle with setting up a mitmproxy on Android. 

I can't say when I'll have time to look into this. If someone wants to fix this sooner, feel free to open a PR.

**Comment by t1mlange** [comment]
I've updated the extension, though, I couldn't reproduce your issue.
