### ISSUE TITLE
Does it enable "Group session for speakers" or "Remote group session"?

### ISSUE THREAD

**Issue by leodurandfr** [timll/spotify-group-session#11]
Hello Tim,

I am wondering if it's about "Group session on speaker" or "Remote group session"?

https://support.spotify.com/us/article/remote-group-session/
https://support.spotify.com/us/article/group-session-on-speaker

Thank you 🙏

**Comment by t1mlange** [comment]
The first one "remote group sessions". But if you start playing on a speaker and then open a remote group session, everyone should be able to add songs to the playlist playing on the speaker.

**Comment by leodurandfr** [comment]
Thank you for the answer. I was hoping it was for "Group session on speaker". I'm looking for a way to let accounts (connected on the same network) to get access to controls my Spotify app player.

**Comment by t1mlange** [comment]
I believe with the newest update, Spotify merged both features into the jam feature. The underlying API stayed the same such that now, the extension should work for both features.
