### ISSUE TITLE
Broken on latest version

### ISSUE THREAD

**Issue by cospin** [timll/spotify-group-session#13]
Hey there, 
In the latest versions, it seems that the extension has stopped working. The UI always displays as if a session had already started (with ID undefined), and it cannot be canceled.

![image](https://github.com/timll/spotify-group-session/assets/2880114/d1a3ae5f-afe6-460f-90e3-9bf40a427697)

Spotify for Windows (64 bits)
1.2.25.1011.g0348b2ea
Spicetify v2.27.2

**Comment by t1mlange** [comment]
Hi,

it seems like Spotify removed some parts we used to find the local device id. I have pushed a fix for this, can you please check if it's fixed for you?

**Comment by cospin** [comment]
Yep, it's working now.
Thank you!
