### ISSUE TITLE
Session creation failed with Premium

### ISSUE THREAD

**Issue by Moquent** [timll/spotify-group-session#14]
Even with Spotify Premium and an active internet connection the session startup failed. It works through mobile though.

![image](https://github.com/timll/spotify-group-session/assets/63721912/18a8fbfe-6bd6-4d51-8d2f-9b207d108f10)

**Comment by madebylydia** [comment]
Can reproduce

**Comment by t1mlange** [comment]
I believe this is related to recent Spotify changes (see https://github.com/spicetify/spicetify-cli/issues/2844). I currently don't have time to add a manual solution, https://github.com/spicetify/spicetify-cli/pull/2846 might fix this.

For now, you could downgrade the Spotify version.

**Comment by rxri** [comment]
hiya, `v2.32.0` should fix this issue ^^

**Comment by cyrus01337** [comment]
Sessions are now created, however, the code is `undefined`. I'm assuming this isn't intentional and tied to the same problem?

**Edit;** I'm assuming my issue was caused by lack of Spotify Premium given I only skimmed the README at the time of writing this.

**Comment by Mlig317** [comment]
still having this issue. any chance it will get looked at?

**Comment by LouisAsanaka** [comment]
It has been a while, but I'm willing to take a look.

**Comment by t1mlange** [comment]
![jam button](https://github.com/user-attachments/assets/49a4ece2-c8c0-4b3e-abb8-e60e137b7862)

At least for me, Spotify has now implemented the behavior natively. You can just right click a song and then :start jam"
