### ISSUE TITLE
New Spotify UI breaks the extention.

### ISSUE THREAD

**Issue by Godwhitelight** [timll/spotify-group-session#15]
![image](https://github.com/user-attachments/assets/2c5e97fb-a89a-4adf-8c62-0b4f70768bbf)
As you can see in the image the new spotify ui breaks that feature and you dont have the option to create a group session.

**Comment by t1mlange** [comment]
![375778848-49a4ece2-c8c0-4b3e-abb8-e60e137b7862](https://github.com/user-attachments/assets/d448326d-f3e6-4bc3-8945-faff4c209ef8)

Spotify's new UI implements the feature natively, no need for an extension anymore. Just right-click on a song.
