### ISSUE TITLE
It requires Spotify Premium to Work!

### ISSUE THREAD

**Issue by parthkhxndelwal** [timll/spotify-group-session#2]
Hi. Does This Feature Requires Spotify Premium to work? I am not able create sessions as it displaying a dialogue box to make sure that account has Spotify prem. .
![image](https://user-images.githubusercontent.com/89642347/157869245-ee8a75e4-3ca2-478b-8a6f-9c66cb370f50.png)

**Comment by t1mlange** [comment]
Yes, you need Spotify premium as written in the readme and shown in the notification.

Spotify group sessions are already available on mobile phones. In the background, group sessions are just a REST API by Spotify. This extension allows the desktop client to use the existing API. Spotify chose to make this a premium feature and thus, the API rejects any requests from non-premium accounts.
