### ISSUE TITLE
[FEATURE] Color music visualizer

### ISSUE THREAD

**Issue by DarkPlayerr** [timll/spotify-group-session#8]
It'd be pretty cool if it was possible for the music graph to be themed with the accent color of the used spicetify theme, instead of the Spotify green if possible.

This is how it looks now
![image](https://user-images.githubusercontent.com/22507352/192068982-8e2b79a7-ec9c-429d-8568-7f1d1002e176.png)

**Comment by t1mlange** [comment]
The music graph is part of Spotify's device menu. You should file this bug against your theme.

**Comment by DarkPlayerr** [comment]
my bad, thanks!
