### ISSUE TITLE
Group Song starts over after 9sec 

### ISSUE THREAD

**Issue by Patyeeee** [timll/spotify-group-session#9]
Hi so Im listening with 1 person and he is the host. After 9 seconds exactly my song starts over but his keeps playing causing a delay.  I've cleared my cache, tried restarting the group session and it didn't help. not sure what do 

Thanks, Pat.

**Comment by Moquent** [comment]
The delay is due to the latency b/w the Spotify app itself, it isn't related to this extension iirc.
